### ISSUE TITLE
Not handling relative chunklists in hls manifest

### ISSUE THREAD

**Issue by scottf-tvw** [Blazemeter/HLSPlugin#12]
playlist is for a live stream that produces relative chunklist manifests.
```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2224095,CODECS="avc1.77.40,mp4a.40.2",RESOLUTION=1920x1080
../../254985/29c28f19/9375922947_TVWAIR_247/chunklist.m3u8
```
your plugin is concatenating improperly when a valid relative path manifest is presented. 

error dump from scan
```timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,IdleTime,Connect,"ulp_buffer_fill","ulp_lag_time","ulp_play_time","ulp_lag_ratio","ulp_lag_ratio_wo_bf","ulp_dwn_time"
1591977723704,527,bzm - Streaming Sampler - media playlist,404,Not Found,Thread Group 1-1,text,false,,585,214,1,1,http://wowzaprod13-i.akamaihd.net/hls/live/254985/29c28f19/../../254985/29c28f19/9375922947_TVWAIR_247/chunklist.m3u8,527,0,0,null,null,null,null,null,null```

**Comment by RicardoPoleo** [comment]
Hello @scottf-tvw.

Thanks for taking the time to report this issue.

We have added this issue to our backlog and we will try to fix it as soon as possible but, to be able to do so, we might need some info, to begin with.

1st: Provide the Version of the Plugin that you are using.
2nd: Can you send us an URL that allows us to reproduce the behavior that you are facing?

Hope to hear from you soon,

Regards,
Ricardo

**Comment by diego-ferrand** [comment]
Hey @scottf-tvw , we just launched a pre-release which should solve this issue. Please check it out and let us know what you think.

**Comment by RicardoPoleo** [comment]
Due to lack of activity, I'll close this issue for now. 

If the issue persists, please reopen it again 😉
