### ISSUE TITLE
Sampler expecting subtitle playlist?

### ISSUE THREAD

**Issue by runenilsenoe** [Blazemeter/HLSPlugin#15]

**Comment by RicardoPoleo** [comment]
Hello, @runenilsenoe

Thanks for reporting issues in the plugging, we really appreciate it.

Could you elaborate more on this? Also, if you could share:

1. The Version of the Plugin that you are using.
2. The URL that allows us to reproduce the behavior that you are facing
3. The log of the error displayed in JMeter

we could tackle the problem faster and help you out.

Hope to hear from you soon,

Regards,
Ricardo

**Comment by runenilsenoe** [comment]
I am sorry, started a post and left it as a draft. we are not going further with this atm.
 
But to explain shortly: 
i get a `PlaylistParsingException` on the subtitles playlist working perfectly in the bitmovin web player. 
The audio and media playlists works perfectly. These are containing the full uri of the subtitles, and referred as secondlevelmanifests, whereas the subtitle playlist reference is directly to the cdn and with just the filenames listed in the playlist

`snippet from master playlist - token's and links are blurred`

`#EXT-X-MEDIA:TYPE=SUBTITLES,NAME="English",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE="eng",GROUP-ID="subs",URI="https://xx.on4cdn.net/live/46724910/xx/playlist_vtt_eng.m3u8"`

`#EXT-X-MEDIA:TYPE=AUDIO,LANGUAGE="fin",NAME="Finnish",AUTOSELECT=YES,DEFAULT=YES,GROUP-ID="program_audio",URI="https://xxproxy.azurewebsites.net/api/SecondLevelManifest?playbackUrl=https%3a%2f%2fxx.on4cdn.net%2flive%2f46724910%2fxx%2fplaylist_fi.m3u8&token=eyJhbGciOiJIUzI1xcCI6IkpXVCJ9.eyJuYmYiOjE1OTQyMTkwNTYsImV4cCIck1NiwiaXNzIjoiaHR0cHM6Ly9icnVuc3RhZCxpicnVuc3RhZHR2In0.1yJXDQW3yP--fdovbdmka5zcuXxgc0G7I"`

**Comment by runenilsenoe** [comment]
Turns out there was multiple subtitle entries with `DEFAULT=YES` and it broke the parsing
